### ISSUE TITLE
delayAfter = 0 does not disable rate slowdown

### ISSUE THREAD

**Issue by begolf** [express-rate-limit/express-slow-down#16]
I am trying to dynamically turn on and off the rate slowdown.  Whenever I set the delayAfter = 0 it defaults to 1 and immediately starts to slow down the requests.  Since this is the only option that supports using a function handler for returning the option value this is the only option we can use to handle this use case.

**Comment by nfriedly** [comment]
Sorry I missed this when it first came in. Also, sorry that the readme was wrong about setting delayAfter to 0. The docs were initially written when express-slow-down was a part of express-rate-limit. It changed to `o` meaning "slow down *every* request" when I moved it into it's own module, but I copied over that part of the readme without realizing it.

However, in your case, I think you want to use the `skip` option to supply a function that returns true or false.
