### ISSUE TITLE
Allow failed requests to count twice

### ISSUE THREAD

**Issue by StephanBijzitter** [express-rate-limit/express-slow-down#20]
Essentially, the current options `skipSuccessfulRequests` and `skipFailedRequests` take `boolean` values which modify the counting behavior by either adding `0` or `1` to the counter. This could be taken a step further:

Introduce two new options:
```
successfulRequestWeight: number 
failedRequestWeight: number
```

Deprecate the existing options:
```
skipSuccessfulRequests = true -> successfulRequestWeight = 0
skipSuccessfulRequests = false -> successfulRequestWeight = 1
skipFailedRequests = true -> failedRequestWeight = 0
skipFailedRequests = false -> failedRequestWeight = 1
```

Update the stores (in a backward-compatible way):
```
increment: (key: any, cb: (err: Error | null, current: number, resetTime: number) => unknown, amount: number = 1)
decrement: (key: any, amount: number = 1)
```

This would allow anyone to configure just how much successful or failed requests contribute towards the limit, while still keeping the options simple.

If you'd like this (or something similar), I'd be happy to provide a pull request for `express-slow-down` and/or `express-rate-limit`

**Comment by nfriedly** [comment]
Hey, sorry for the slow response, somehow notifications got turned off for this repo.

That's a cool idea, but I'm a little hesitant on it just because of the complexity it adds. I think some of the other rate-limiters out there do support request weights, though, so that might be a better choice in your case.

**Comment by nfriedly** [comment]
Going to go ahead and close this, since I don't think we're going to implement the feature.
