### ISSUE TITLE
req.ip is undefiend on production

### ISSUE THREAD

**Issue by RafeSafari** [express-rate-limit/express-slow-down#9]
i was using `onLimitReached` to log the possible attacker's ip, but figured out that `req.ip` is undefiend.
in addition, the limit is applying to all computers, because everyone's `req.ip` is undefiend!

**Comment by nfriedly** [comment]
Are you using it with express? all express-slow-down does is read the `req.ip` value that [express normally sets](http://expressjs.com/en/4x/api.html#req.ip).

I suppose you could supply a custom `keyGenerator` method if your setup has the IP stored somewhere else.
